on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  house-keeping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep mkdocs to 10
        uses: actions/delete-package-versions@v4.1.1
        with:
          package-name: 'mkdocs'
          package-type: 'container'
          min-versions-to-keep: 10
          token: ${{ secrets.GITHUB_TOKEN }}
