name: Build MKDocs ARM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dockerbackend:
    name: Build and store backend docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v4.1.0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Cache Docker layers
        uses: actions/cache@v3.3.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker Hub login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GitHub container Registry login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build and Push Arm
        id: docker_build_arm
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./
          file: ./DockerfileM1
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ghcr.io/hcl-tech-software/mkdocs:M1
            ghcr.io/hcl-tech-software/mkdocs:arm-${{ env.date }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Image digest arm
        run: echo ${{ steps.docker_build_arm.outputs.digest }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ghcr.io/hcl-tech-software/mkdocs:latest
            ghcr.io/hcl-tech-software/mkdocs:v-${{ env.date }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
